// This file was generated by a tool; you should avoid making direct changes.
// Consider using 'partial classes' to extend these types
// Input: Message.proto

#pragma warning disable CS1591, CS0612, CS3021, IDE1006
namespace Message
{

    [global::ProtoBuf.ProtoContract(Name = @"Login_PCK")]
    public partial class LoginPCK : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
        public Head Head { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body", IsRequired = true)]
        public LoginBody Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"Voice_PCK")]
    public partial class VoicePCK : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"body", IsRequired = true)]
        public VoiceBody Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Head : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"cmd", IsRequired = true)]
        public Cmd Cmd { get; set; } = Cmd.AccSvcRegist;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Login_Body")]
    public partial class LoginBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2)]
        [global::System.ComponentModel.DefaultValue("")]
        public string Nickname
        {
            get { return __pbn__Nickname ?? ""; }
            set { __pbn__Nickname = value; }
        }
        public bool ShouldSerializeNickname() => __pbn__Nickname != null;
        public void ResetNickname() => __pbn__Nickname = null;
        private string __pbn__Nickname;

        [global::ProtoBuf.ProtoMember(3)]
        public int worldID
        {
            get { return __pbn__worldID.GetValueOrDefault(); }
            set { __pbn__worldID = value; }
        }
        public bool ShouldSerializeworldID() => __pbn__worldID != null;
        public void ResetworldID() => __pbn__worldID = null;
        private int? __pbn__worldID;

        [global::ProtoBuf.ProtoMember(4)]
        [global::System.ComponentModel.DefaultValue("")]
        public string battleIp
        {
            get { return __pbn__battleIp ?? ""; }
            set { __pbn__battleIp = value; }
        }
        public bool ShouldSerializebattleIp() => __pbn__battleIp != null;
        public void ResetbattleIp() => __pbn__battleIp = null;
        private string __pbn__battleIp;

        [global::ProtoBuf.ProtoMember(5, Name = @"battleport")]
        public int Battleport
        {
            get { return __pbn__Battleport.GetValueOrDefault(); }
            set { __pbn__Battleport = value; }
        }
        public bool ShouldSerializeBattleport() => __pbn__Battleport != null;
        public void ResetBattleport() => __pbn__Battleport = null;
        private int? __pbn__Battleport;

        [global::ProtoBuf.ProtoMember(6, Name = @"players")]
        public global::System.Collections.Generic.List<Player> Players { get; } = new global::System.Collections.Generic.List<Player>();

        [global::ProtoBuf.ProtoMember(7)]
        public long DateTime
        {
            get { return __pbn__DateTime.GetValueOrDefault(); }
            set { __pbn__DateTime = value; }
        }
        public bool ShouldSerializeDateTime() => __pbn__DateTime != null;
        public void ResetDateTime() => __pbn__DateTime = null;
        private long? __pbn__DateTime;

        [global::ProtoBuf.ProtoMember(8)]
        [global::System.ComponentModel.DefaultValue("")]
        public string VoiceIp
        {
            get { return __pbn__VoiceIp ?? ""; }
            set { __pbn__VoiceIp = value; }
        }
        public bool ShouldSerializeVoiceIp() => __pbn__VoiceIp != null;
        public void ResetVoiceIp() => __pbn__VoiceIp = null;
        private string __pbn__VoiceIp;

        [global::ProtoBuf.ProtoMember(9)]
        public int Voiceport
        {
            get { return __pbn__Voiceport.GetValueOrDefault(); }
            set { __pbn__Voiceport = value; }
        }
        public bool ShouldSerializeVoiceport() => __pbn__Voiceport != null;
        public void ResetVoiceport() => __pbn__Voiceport = null;
        private int? __pbn__Voiceport;

        [global::ProtoBuf.ProtoMember(10)]
        public int playerCount
        {
            get { return __pbn__playerCount.GetValueOrDefault(); }
            set { __pbn__playerCount = value; }
        }
        public bool ShouldSerializeplayerCount() => __pbn__playerCount != null;
        public void ResetplayerCount() => __pbn__playerCount = null;
        private int? __pbn__playerCount;

        [global::ProtoBuf.ProtoMember(11)]
        public bool IsFull
        {
            get { return __pbn__IsFull.GetValueOrDefault(); }
            set { __pbn__IsFull = value; }
        }
        public bool ShouldSerializeIsFull() => __pbn__IsFull != null;
        public void ResetIsFull() => __pbn__IsFull = null;
        private bool? __pbn__IsFull;

        [global::ProtoBuf.ProtoMember(12)]
        public int TeamID
        {
            get { return __pbn__TeamID.GetValueOrDefault(); }
            set { __pbn__TeamID = value; }
        }
        public bool ShouldSerializeTeamID() => __pbn__TeamID != null;
        public void ResetTeamID() => __pbn__TeamID = null;
        private int? __pbn__TeamID;

        [global::ProtoBuf.ProtoMember(13, Name = @"token")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Token
        {
            get { return __pbn__Token ?? ""; }
            set { __pbn__Token = value; }
        }
        public bool ShouldSerializeToken() => __pbn__Token != null;
        public void ResetToken() => __pbn__Token = null;
        private string __pbn__Token;

    }

    [global::ProtoBuf.ProtoContract(Name = @"Voice_Body")]
    public partial class VoiceBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"audioFloat")]
        public float[] audioFloats { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public string NickName { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"Mysql_PCK")]
    public partial class MysqlPCK : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
        public Head Head { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body", IsRequired = true)]
        public MysqlBody Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"Mysql_Body")]
    public partial class MysqlBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"password", IsRequired = true)]
        public string Password { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"token", IsRequired = true)]
        public string Token { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public bool Successful { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Player : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, IsRequired = true)]
        public string nickName { get; set; }

        [global::ProtoBuf.ProtoMember(4)]
        public int TeamId
        {
            get { return __pbn__TeamId.GetValueOrDefault(); }
            set { __pbn__TeamId = value; }
        }
        public bool ShouldSerializeTeamId() => __pbn__TeamId != null;
        public void ResetTeamId() => __pbn__TeamId = null;
        private int? __pbn__TeamId;

        [global::ProtoBuf.ProtoMember(5, Name = @"position")]
        public Vector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(6)]
        public Vector3 moveDir { get; set; }

        [global::ProtoBuf.ProtoMember(7, Name = @"rotation")]
        public Vector3 Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(9)]
        public bool IsMove
        {
            get { return __pbn__IsMove.GetValueOrDefault(); }
            set { __pbn__IsMove = value; }
        }
        public bool ShouldSerializeIsMove() => __pbn__IsMove != null;
        public void ResetIsMove() => __pbn__IsMove = null;
        private bool? __pbn__IsMove;

        [global::ProtoBuf.ProtoMember(10)]
        public long DateTime
        {
            get { return __pbn__DateTime.GetValueOrDefault(); }
            set { __pbn__DateTime = value; }
        }
        public bool ShouldSerializeDateTime() => __pbn__DateTime != null;
        public void ResetDateTime() => __pbn__DateTime = null;
        private long? __pbn__DateTime;

        [global::ProtoBuf.ProtoMember(11, Name = @"currentspeed")]
        public float Currentspeed
        {
            get { return __pbn__Currentspeed.GetValueOrDefault(); }
            set { __pbn__Currentspeed = value; }
        }
        public bool ShouldSerializeCurrentspeed() => __pbn__Currentspeed != null;
        public void ResetCurrentspeed() => __pbn__Currentspeed = null;
        private float? __pbn__Currentspeed;

        [global::ProtoBuf.ProtoMember(12)]
        public Vector3 Headrotation { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"World_PCK")]
    public partial class WorldPCK : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"head", IsRequired = true)]
        public Head Head { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"body", IsRequired = true)]
        public WorldBody Body { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"World_Body")]
    public partial class WorldBody : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"uid", IsRequired = true)]
        public string Uid { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"position")]
        public Vector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(3)]
        public Vector3 moveDir { get; set; }

        [global::ProtoBuf.ProtoMember(4, Name = @"rotation")]
        public Vector3 Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(5)]
        public bool IsFire
        {
            get { return __pbn__IsFire.GetValueOrDefault(); }
            set { __pbn__IsFire = value; }
        }
        public bool ShouldSerializeIsFire() => __pbn__IsFire != null;
        public void ResetIsFire() => __pbn__IsFire = null;
        private bool? __pbn__IsFire;

        [global::ProtoBuf.ProtoMember(6)]
        public bool IsMove
        {
            get { return __pbn__IsMove.GetValueOrDefault(); }
            set { __pbn__IsMove = value; }
        }
        public bool ShouldSerializeIsMove() => __pbn__IsMove != null;
        public void ResetIsMove() => __pbn__IsMove = null;
        private bool? __pbn__IsMove;

        [global::ProtoBuf.ProtoMember(7)]
        public bool IsFast
        {
            get { return __pbn__IsFast.GetValueOrDefault(); }
            set { __pbn__IsFast = value; }
        }
        public bool ShouldSerializeIsFast() => __pbn__IsFast != null;
        public void ResetIsFast() => __pbn__IsFast = null;
        private bool? __pbn__IsFast;

        [global::ProtoBuf.ProtoMember(10)]
        public int GrabItemID
        {
            get { return __pbn__GrabItemID.GetValueOrDefault(); }
            set { __pbn__GrabItemID = value; }
        }
        public bool ShouldSerializeGrabItemID() => __pbn__GrabItemID != null;
        public void ResetGrabItemID() => __pbn__GrabItemID = null;
        private int? __pbn__GrabItemID;

        [global::ProtoBuf.ProtoMember(11)]
        public long DateTime
        {
            get { return __pbn__DateTime.GetValueOrDefault(); }
            set { __pbn__DateTime = value; }
        }
        public bool ShouldSerializeDateTime() => __pbn__DateTime != null;
        public void ResetDateTime() => __pbn__DateTime = null;
        private long? __pbn__DateTime;

        [global::ProtoBuf.ProtoMember(12, Name = @"players")]
        public global::System.Collections.Generic.List<Player> Players { get; } = new global::System.Collections.Generic.List<Player>();

        [global::ProtoBuf.ProtoMember(13, Name = @"score", IsRequired = true)]
        public int Score { get; set; }

        [global::ProtoBuf.ProtoMember(14, IsRequired = true)]
        public string nickName { get; set; }

        [global::ProtoBuf.ProtoMember(15, Name = @"tools")]
        public global::System.Collections.Generic.List<ToolConfig> Tools { get; } = new global::System.Collections.Generic.List<ToolConfig>();

        [global::ProtoBuf.ProtoMember(16)]
        public int itemID
        {
            get { return __pbn__itemID.GetValueOrDefault(); }
            set { __pbn__itemID = value; }
        }
        public bool ShouldSerializeitemID() => __pbn__itemID != null;
        public void ResetitemID() => __pbn__itemID = null;
        private int? __pbn__itemID;

        [global::ProtoBuf.ProtoMember(17)]
        public Vector3 Headrotation { get; set; }

        [global::ProtoBuf.ProtoMember(18)]
        public bool IsSitDown
        {
            get { return __pbn__IsSitDown.GetValueOrDefault(); }
            set { __pbn__IsSitDown = value; }
        }
        public bool ShouldSerializeIsSitDown() => __pbn__IsSitDown != null;
        public void ResetIsSitDown() => __pbn__IsSitDown = null;
        private bool? __pbn__IsSitDown;

        [global::ProtoBuf.ProtoMember(19)]
        [global::System.ComponentModel.DefaultValue("")]
        public string EndTime
        {
            get { return __pbn__EndTime ?? ""; }
            set { __pbn__EndTime = value; }
        }
        public bool ShouldSerializeEndTime() => __pbn__EndTime != null;
        public void ResetEndTime() => __pbn__EndTime = null;
        private string __pbn__EndTime;

        [global::ProtoBuf.ProtoMember(20)]
        public int WaiterNowPlayerCount
        {
            get { return __pbn__WaiterNowPlayerCount.GetValueOrDefault(); }
            set { __pbn__WaiterNowPlayerCount = value; }
        }
        public bool ShouldSerializeWaiterNowPlayerCount() => __pbn__WaiterNowPlayerCount != null;
        public void ResetWaiterNowPlayerCount() => __pbn__WaiterNowPlayerCount = null;
        private int? __pbn__WaiterNowPlayerCount;

        [global::ProtoBuf.ProtoMember(21)]
        public int WaiterMax
        {
            get { return __pbn__WaiterMax.GetValueOrDefault(); }
            set { __pbn__WaiterMax = value; }
        }
        public bool ShouldSerializeWaiterMax() => __pbn__WaiterMax != null;
        public void ResetWaiterMax() => __pbn__WaiterMax = null;
        private int? __pbn__WaiterMax;

        [global::ProtoBuf.ProtoMember(22)]
        public bool IsLocalNetwork
        {
            get { return __pbn__IsLocalNetwork.GetValueOrDefault(); }
            set { __pbn__IsLocalNetwork = value; }
        }
        public bool ShouldSerializeIsLocalNetwork() => __pbn__IsLocalNetwork != null;
        public void ResetIsLocalNetwork() => __pbn__IsLocalNetwork = null;
        private bool? __pbn__IsLocalNetwork;

        [global::ProtoBuf.ProtoMember(23)]
        public int TeamID
        {
            get { return __pbn__TeamID.GetValueOrDefault(); }
            set { __pbn__TeamID = value; }
        }
        public bool ShouldSerializeTeamID() => __pbn__TeamID != null;
        public void ResetTeamID() => __pbn__TeamID = null;
        private int? __pbn__TeamID;

        [global::ProtoBuf.ProtoMember(24)]
        [global::System.ComponentModel.DefaultValue("")]
        public string MarkString
        {
            get { return __pbn__MarkString ?? ""; }
            set { __pbn__MarkString = value; }
        }
        public bool ShouldSerializeMarkString() => __pbn__MarkString != null;
        public void ResetMarkString() => __pbn__MarkString = null;
        private string __pbn__MarkString;

        [global::ProtoBuf.ProtoMember(25)]
        public Vector3 MarkPosition { get; set; }

        [global::ProtoBuf.ProtoMember(26)]
        [global::System.ComponentModel.DefaultValue("")]
        public string MarkName
        {
            get { return __pbn__MarkName ?? ""; }
            set { __pbn__MarkName = value; }
        }
        public bool ShouldSerializeMarkName() => __pbn__MarkName != null;
        public void ResetMarkName() => __pbn__MarkName = null;
        private string __pbn__MarkName;

        [global::ProtoBuf.ProtoMember(27)]
        public float UseTimeAddTime
        {
            get { return __pbn__UseTimeAddTime.GetValueOrDefault(); }
            set { __pbn__UseTimeAddTime = value; }
        }
        public bool ShouldSerializeUseTimeAddTime() => __pbn__UseTimeAddTime != null;
        public void ResetUseTimeAddTime() => __pbn__UseTimeAddTime = null;
        private float? __pbn__UseTimeAddTime;

        [global::ProtoBuf.ProtoMember(28)]
        public int FireSelfType
        {
            get { return __pbn__FireSelfType.GetValueOrDefault(); }
            set { __pbn__FireSelfType = value; }
        }
        public bool ShouldSerializeFireSelfType() => __pbn__FireSelfType != null;
        public void ResetFireSelfType() => __pbn__FireSelfType = null;
        private int? __pbn__FireSelfType;

        [global::ProtoBuf.ProtoMember(29)]
        public int Damage
        {
            get { return __pbn__Damage.GetValueOrDefault(); }
            set { __pbn__Damage = value; }
        }
        public bool ShouldSerializeDamage() => __pbn__Damage != null;
        public void ResetDamage() => __pbn__Damage = null;
        private int? __pbn__Damage;

        [global::ProtoBuf.ProtoMember(30)]
        public int CurrentHealthy
        {
            get { return __pbn__CurrentHealthy.GetValueOrDefault(); }
            set { __pbn__CurrentHealthy = value; }
        }
        public bool ShouldSerializeCurrentHealthy() => __pbn__CurrentHealthy != null;
        public void ResetCurrentHealthy() => __pbn__CurrentHealthy = null;
        private int? __pbn__CurrentHealthy;

        [global::ProtoBuf.ProtoMember(31)]
        public int SaveProgress
        {
            get { return __pbn__SaveProgress.GetValueOrDefault(); }
            set { __pbn__SaveProgress = value; }
        }
        public bool ShouldSerializeSaveProgress() => __pbn__SaveProgress != null;
        public void ResetSaveProgress() => __pbn__SaveProgress = null;
        private int? __pbn__SaveProgress;

        [global::ProtoBuf.ProtoMember(32)]
        public int FixHealthy
        {
            get { return __pbn__FixHealthy.GetValueOrDefault(); }
            set { __pbn__FixHealthy = value; }
        }
        public bool ShouldSerializeFixHealthy() => __pbn__FixHealthy != null;
        public void ResetFixHealthy() => __pbn__FixHealthy = null;
        private int? __pbn__FixHealthy;

        [global::ProtoBuf.ProtoMember(33)]
        public bool NearBounds
        {
            get { return __pbn__NearBounds.GetValueOrDefault(); }
            set { __pbn__NearBounds = value; }
        }
        public bool ShouldSerializeNearBounds() => __pbn__NearBounds != null;
        public void ResetNearBounds() => __pbn__NearBounds = null;
        private bool? __pbn__NearBounds;

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class ToolConfig : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"position", IsRequired = true)]
        public Vector3 Position { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"rotation", IsRequired = true)]
        public Vector3 Rotation { get; set; }

        [global::ProtoBuf.ProtoMember(3, IsRequired = true)]
        public int ToolsID { get; set; }

        [global::ProtoBuf.ProtoMember(4, IsRequired = true)]
        public int NetworkID { get; set; }

    }

    [global::ProtoBuf.ProtoContract()]
    public partial class Vector3 : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"x", IsRequired = true)]
        public float X { get; set; }

        [global::ProtoBuf.ProtoMember(2, Name = @"y", IsRequired = true)]
        public float Y { get; set; }

        [global::ProtoBuf.ProtoMember(3, Name = @"z", IsRequired = true)]
        public float Z { get; set; }

    }

    [global::ProtoBuf.ProtoContract(Name = @"CMD")]
    public enum Cmd
    {
        [global::ProtoBuf.ProtoEnum(Name = @"AccSvc_Regist")]
        AccSvcRegist = 1,
        [global::ProtoBuf.ProtoEnum(Name = @"AccSvc_Join")]
        AccSvcJoin = 2,
        [global::ProtoBuf.ProtoEnum(Name = @"AccSvc_TimeSync")]
        AccSvcTimeSync = 3,
        [global::ProtoBuf.ProtoEnum(Name = @"MainBattleSvc_Search")]
        MainBattleSvcSearch = 4,
        [global::ProtoBuf.ProtoEnum(Name = @"MainBattleSvc_AllowEnter")]
        MainBattleSvcAllowEnter = 5,
        [global::ProtoBuf.ProtoEnum(Name = @"MainBattleSvc_RefuseEnter")]
        MainBattleSvcRefuseEnter = 6,
        [global::ProtoBuf.ProtoEnum(Name = @"World_RegistPlayer")]
        WorldRegistPlayer = 7,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Move")]
        WorldMove = 8,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Fire")]
        WorldFire = 9,
        [global::ProtoBuf.ProtoEnum(Name = @"World_AddBuffer")]
        WorldAddBuffer = 10,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Score")]
        WorldScore = 11,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Grab")]
        WorldGrab = 12,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Throw")]
        WorldThrow = 13,
        [global::ProtoBuf.ProtoEnum(Name = @"World_UnItemFire")]
        WorldUnItemFire = 14,
        [global::ProtoBuf.ProtoEnum(Name = @"World_ItemFire")]
        WorldItemFire = 15,
        [global::ProtoBuf.ProtoEnum(Name = @"World_SitDown")]
        WorldSitDown = 16,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PowerStopFire")]
        WorldPowerStopFire = 17,
        [global::ProtoBuf.ProtoEnum(Name = @"World_EndTimeAsync")]
        WorldEndTimeAsync = 18,
        [global::ProtoBuf.ProtoEnum(Name = @"World_WaitPlayer")]
        WorldWaitPlayer = 19,
        [global::ProtoBuf.ProtoEnum(Name = @"World_FireSpawn")]
        WorldFireSpawn = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Iteraction")]
        WorldIteraction = 21,
        [global::ProtoBuf.ProtoEnum(Name = @"World_FireWinner")]
        WorldFireWinner = 22,
        [global::ProtoBuf.ProtoEnum(Name = @"World_UnFireWinner")]
        WorldUnFireWinner = 23,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Mark")]
        WorldMark = 24,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PlayerFireSelf")]
        WorldPlayerFireSelf = 25,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PlayerUnFireSelf")]
        WorldPlayerUnFireSelf = 26,
        [global::ProtoBuf.ProtoEnum(Name = @"World_ToolTimeAdd")]
        WorldToolTimeAdd = 27,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Jump")]
        WorldJump = 28,
        [global::ProtoBuf.ProtoEnum(Name = @"World_GameStart")]
        WorldGameStart = 29,
        [global::ProtoBuf.ProtoEnum(Name = @"World_GameStartUnFireSpawn")]
        WorldGameStartUnFireSpawn = 30,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PlayerDeathDown")]
        WorldPlayerDeathDown = 31,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PlayerDamage")]
        WorldPlayerDamage = 32,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PlayerSave")]
        WorldPlayerSave = 33,
        [global::ProtoBuf.ProtoEnum(Name = @"World_RobotMove")]
        WorldRobotMove = 34,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PropSpawn")]
        WorldPropSpawn = 35,
        [global::ProtoBuf.ProtoEnum(Name = @"World_PropGrab")]
        WorldPropGrab = 36,
        [global::ProtoBuf.ProtoEnum(Name = @"World_RobotOpen")]
        WorldRobotOpen = 37,
        [global::ProtoBuf.ProtoEnum(Name = @"World_RobotFire")]
        WorldRobotFire = 38,
        [global::ProtoBuf.ProtoEnum(Name = @"World_RobotUnFire")]
        WorldRobotUnFire = 39,
        [global::ProtoBuf.ProtoEnum(Name = @"World_Exit")]
        WorldExit = 40,
        [global::ProtoBuf.ProtoEnum(Name = @"Mysql_login")]
        Mysqllogin = 20,
        [global::ProtoBuf.ProtoEnum(Name = @"Mysql_Quit")]
        MysqlQuit = 21,
    }

}

#pragma warning restore CS1591, CS0612, CS3021, IDE1006
